# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server_api.proto',
  package='MicroService',
  syntax='proto3',
  serialized_pb=_b('\n\x10server_api.proto\x12\x0cMicroService\"\x18\n\x05\x45mpty\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x15\n\x05\x43hunk\x12\x0c\n\x04\x62lob\x18\x01 \x01(\x0c\"B\n\tSignupReq\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0craw_password\x18\x06 \x01(\t\"2\n\x08LoginReq\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x14\n\x0craw_password\x18\x03 \x01(\t\"$\n\x10\x43heckUsernameReq\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1e\n\rCheckEmailReq\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"D\n\x10\x43hangeProfileReq\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x0b\n\x03\x62io\x18\x06 \x01(\t\"\x1f\n\x0e\x43hangeEmailReq\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"!\n\nSignupResp\x12\x13\n\x0bsession_key\x18\x01 \x01(\t\" \n\tLoginResp\x12\x13\n\x0bsession_key\x18\x01 \x01(\t2\xda\x04\n\tServerApi\x12=\n\x06signup\x12\x17.MicroService.SignupReq\x1a\x18.MicroService.SignupResp\"\x00\x12:\n\x0cis_logged_in\x12\x13.MicroService.Empty\x1a\x13.MicroService.Empty\"\x00\x12:\n\x05login\x12\x16.MicroService.LoginReq\x1a\x17.MicroService.LoginResp\"\x00\x12\x34\n\x06logout\x12\x13.MicroService.Empty\x1a\x13.MicroService.Empty\"\x00\x12N\n\x15is_username_available\x12\x1e.MicroService.CheckUsernameReq\x1a\x13.MicroService.Empty\"\x00\x12H\n\x12is_email_available\x12\x1b.MicroService.CheckEmailReq\x1a\x13.MicroService.Empty\"\x00\x12G\n\x0e\x63hange_profile\x12\x1e.MicroService.ChangeProfileReq\x1a\x13.MicroService.Empty\"\x00\x12\x43\n\x0c\x63hange_email\x12\x1c.MicroService.ChangeEmailReq\x1a\x13.MicroService.Empty\"\x00\x12\x38\n\x08get_file\x12\x13.MicroService.Empty\x1a\x13.MicroService.Chunk\"\x00\x30\x01\x42\x33\n\x1cio.grpc.trippapp.microservicB\x11MicroServiceProtoP\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='MicroService.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='MicroService.Empty.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=58,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='MicroService.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blob', full_name='MicroService.Chunk.blob', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=81,
)


_SIGNUPREQ = _descriptor.Descriptor(
  name='SignupReq',
  full_name='MicroService.SignupReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='MicroService.SignupReq.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='MicroService.SignupReq.email', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_password', full_name='MicroService.SignupReq.raw_password', index=2,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=149,
)


_LOGINREQ = _descriptor.Descriptor(
  name='LoginReq',
  full_name='MicroService.LoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='MicroService.LoginReq.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_password', full_name='MicroService.LoginReq.raw_password', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=201,
)


_CHECKUSERNAMEREQ = _descriptor.Descriptor(
  name='CheckUsernameReq',
  full_name='MicroService.CheckUsernameReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='MicroService.CheckUsernameReq.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=239,
)


_CHECKEMAILREQ = _descriptor.Descriptor(
  name='CheckEmailReq',
  full_name='MicroService.CheckEmailReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='MicroService.CheckEmailReq.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=271,
)


_CHANGEPROFILEREQ = _descriptor.Descriptor(
  name='ChangeProfileReq',
  full_name='MicroService.ChangeProfileReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='MicroService.ChangeProfileReq.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='MicroService.ChangeProfileReq.full_name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bio', full_name='MicroService.ChangeProfileReq.bio', index=2,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=341,
)


_CHANGEEMAILREQ = _descriptor.Descriptor(
  name='ChangeEmailReq',
  full_name='MicroService.ChangeEmailReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='MicroService.ChangeEmailReq.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=374,
)


_SIGNUPRESP = _descriptor.Descriptor(
  name='SignupResp',
  full_name='MicroService.SignupResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_key', full_name='MicroService.SignupResp.session_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=409,
)


_LOGINRESP = _descriptor.Descriptor(
  name='LoginResp',
  full_name='MicroService.LoginResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_key', full_name='MicroService.LoginResp.session_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=443,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['SignupReq'] = _SIGNUPREQ
DESCRIPTOR.message_types_by_name['LoginReq'] = _LOGINREQ
DESCRIPTOR.message_types_by_name['CheckUsernameReq'] = _CHECKUSERNAMEREQ
DESCRIPTOR.message_types_by_name['CheckEmailReq'] = _CHECKEMAILREQ
DESCRIPTOR.message_types_by_name['ChangeProfileReq'] = _CHANGEPROFILEREQ
DESCRIPTOR.message_types_by_name['ChangeEmailReq'] = _CHANGEEMAILREQ
DESCRIPTOR.message_types_by_name['SignupResp'] = _SIGNUPRESP
DESCRIPTOR.message_types_by_name['LoginResp'] = _LOGINRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), dict(
  DESCRIPTOR = _CHUNK,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.Chunk)
  ))
_sym_db.RegisterMessage(Chunk)

SignupReq = _reflection.GeneratedProtocolMessageType('SignupReq', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPREQ,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.SignupReq)
  ))
_sym_db.RegisterMessage(SignupReq)

LoginReq = _reflection.GeneratedProtocolMessageType('LoginReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQ,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.LoginReq)
  ))
_sym_db.RegisterMessage(LoginReq)

CheckUsernameReq = _reflection.GeneratedProtocolMessageType('CheckUsernameReq', (_message.Message,), dict(
  DESCRIPTOR = _CHECKUSERNAMEREQ,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.CheckUsernameReq)
  ))
_sym_db.RegisterMessage(CheckUsernameReq)

CheckEmailReq = _reflection.GeneratedProtocolMessageType('CheckEmailReq', (_message.Message,), dict(
  DESCRIPTOR = _CHECKEMAILREQ,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.CheckEmailReq)
  ))
_sym_db.RegisterMessage(CheckEmailReq)

ChangeProfileReq = _reflection.GeneratedProtocolMessageType('ChangeProfileReq', (_message.Message,), dict(
  DESCRIPTOR = _CHANGEPROFILEREQ,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.ChangeProfileReq)
  ))
_sym_db.RegisterMessage(ChangeProfileReq)

ChangeEmailReq = _reflection.GeneratedProtocolMessageType('ChangeEmailReq', (_message.Message,), dict(
  DESCRIPTOR = _CHANGEEMAILREQ,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.ChangeEmailReq)
  ))
_sym_db.RegisterMessage(ChangeEmailReq)

SignupResp = _reflection.GeneratedProtocolMessageType('SignupResp', (_message.Message,), dict(
  DESCRIPTOR = _SIGNUPRESP,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.SignupResp)
  ))
_sym_db.RegisterMessage(SignupResp)

LoginResp = _reflection.GeneratedProtocolMessageType('LoginResp', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESP,
  __module__ = 'server_api_pb2'
  # @@protoc_insertion_point(class_scope:MicroService.LoginResp)
  ))
_sym_db.RegisterMessage(LoginResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034io.grpc.trippapp.microservicB\021MicroServiceProtoP\001'))

_SERVERAPI = _descriptor.ServiceDescriptor(
  name='ServerApi',
  full_name='MicroService.ServerApi',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=446,
  serialized_end=1048,
  methods=[
  _descriptor.MethodDescriptor(
    name='signup',
    full_name='MicroService.ServerApi.signup',
    index=0,
    containing_service=None,
    input_type=_SIGNUPREQ,
    output_type=_SIGNUPRESP,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='is_logged_in',
    full_name='MicroService.ServerApi.is_logged_in',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='login',
    full_name='MicroService.ServerApi.login',
    index=2,
    containing_service=None,
    input_type=_LOGINREQ,
    output_type=_LOGINRESP,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='logout',
    full_name='MicroService.ServerApi.logout',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='is_username_available',
    full_name='MicroService.ServerApi.is_username_available',
    index=4,
    containing_service=None,
    input_type=_CHECKUSERNAMEREQ,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='is_email_available',
    full_name='MicroService.ServerApi.is_email_available',
    index=5,
    containing_service=None,
    input_type=_CHECKEMAILREQ,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='change_profile',
    full_name='MicroService.ServerApi.change_profile',
    index=6,
    containing_service=None,
    input_type=_CHANGEPROFILEREQ,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='change_email',
    full_name='MicroService.ServerApi.change_email',
    index=7,
    containing_service=None,
    input_type=_CHANGEEMAILREQ,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_file',
    full_name='MicroService.ServerApi.get_file',
    index=8,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CHUNK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERAPI)

DESCRIPTOR.services_by_name['ServerApi'] = _SERVERAPI

# @@protoc_insertion_point(module_scope)
