# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import account_pb2 as account__pb2


class AccountServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.login = channel.unary_unary(
        '/Account.AccountService/login',
        request_serializer=account__pb2.LoginReq.SerializeToString,
        response_deserializer=account__pb2.LoginResp.FromString,
        )
    self.signup = channel.unary_unary(
        '/Account.AccountService/signup',
        request_serializer=account__pb2.SignupReq.SerializeToString,
        response_deserializer=account__pb2.SignupResp.FromString,
        )
    self.get_user = channel.unary_unary(
        '/Account.AccountService/get_user',
        request_serializer=account__pb2.UserReq.SerializeToString,
        response_deserializer=account__pb2.UserResp.FromString,
        )
    self.get_account = channel.unary_unary(
        '/Account.AccountService/get_account',
        request_serializer=account__pb2.AccountReq.SerializeToString,
        response_deserializer=account__pb2.AccountResp.FromString,
        )
    self.get_followers = channel.unary_unary(
        '/Account.AccountService/get_followers',
        request_serializer=account__pb2.UserReq.SerializeToString,
        response_deserializer=account__pb2.FollowersResp.FromString,
        )
    self.get_following = channel.unary_unary(
        '/Account.AccountService/get_following',
        request_serializer=account__pb2.UserReq.SerializeToString,
        response_deserializer=account__pb2.FollowingResp.FromString,
        )
    self.change_user = channel.unary_unary(
        '/Account.AccountService/change_user',
        request_serializer=account__pb2.ChangeUserReq.SerializeToString,
        response_deserializer=account__pb2.UserSummary.FromString,
        )
    self.change_profile = channel.unary_unary(
        '/Account.AccountService/change_profile',
        request_serializer=account__pb2.ChangeProfileReq.SerializeToString,
        response_deserializer=account__pb2.UserSummary.FromString,
        )
    self.follow = channel.unary_unary(
        '/Account.AccountService/follow',
        request_serializer=account__pb2.FollowReq.SerializeToString,
        response_deserializer=account__pb2.FollowResp.FromString,
        )
    self.unfollow = channel.unary_unary(
        '/Account.AccountService/unfollow',
        request_serializer=account__pb2.UnfollowReq.SerializeToString,
        response_deserializer=account__pb2.UnfollowResp.FromString,
        )


class AccountServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def signup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_account(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_followers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_following(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def change_user(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def change_profile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def follow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def unfollow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'login': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=account__pb2.LoginReq.FromString,
          response_serializer=account__pb2.LoginResp.SerializeToString,
      ),
      'signup': grpc.unary_unary_rpc_method_handler(
          servicer.signup,
          request_deserializer=account__pb2.SignupReq.FromString,
          response_serializer=account__pb2.SignupResp.SerializeToString,
      ),
      'get_user': grpc.unary_unary_rpc_method_handler(
          servicer.get_user,
          request_deserializer=account__pb2.UserReq.FromString,
          response_serializer=account__pb2.UserResp.SerializeToString,
      ),
      'get_account': grpc.unary_unary_rpc_method_handler(
          servicer.get_account,
          request_deserializer=account__pb2.AccountReq.FromString,
          response_serializer=account__pb2.AccountResp.SerializeToString,
      ),
      'get_followers': grpc.unary_unary_rpc_method_handler(
          servicer.get_followers,
          request_deserializer=account__pb2.UserReq.FromString,
          response_serializer=account__pb2.FollowersResp.SerializeToString,
      ),
      'get_following': grpc.unary_unary_rpc_method_handler(
          servicer.get_following,
          request_deserializer=account__pb2.UserReq.FromString,
          response_serializer=account__pb2.FollowingResp.SerializeToString,
      ),
      'change_user': grpc.unary_unary_rpc_method_handler(
          servicer.change_user,
          request_deserializer=account__pb2.ChangeUserReq.FromString,
          response_serializer=account__pb2.UserSummary.SerializeToString,
      ),
      'change_profile': grpc.unary_unary_rpc_method_handler(
          servicer.change_profile,
          request_deserializer=account__pb2.ChangeProfileReq.FromString,
          response_serializer=account__pb2.UserSummary.SerializeToString,
      ),
      'follow': grpc.unary_unary_rpc_method_handler(
          servicer.follow,
          request_deserializer=account__pb2.FollowReq.FromString,
          response_serializer=account__pb2.FollowResp.SerializeToString,
      ),
      'unfollow': grpc.unary_unary_rpc_method_handler(
          servicer.unfollow,
          request_deserializer=account__pb2.UnfollowReq.FromString,
          response_serializer=account__pb2.UnfollowResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Account.AccountService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
